# Generated by Django 3.2.16 on 2022-10-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_answersection_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsection',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questionsection',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnswerSection',
        ),
        migrations.DeleteModel(
            name='QuestionSection',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
